package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

/*
GetCommitsParams contains all the parameters to send to the API endpoint
for the get commits operation typically these are written to a http.Request
*/
type GetCommitsParams struct {
	Project string

	Repo string
}

// WriteToRequest writes these params to a swagger request
func (o *GetCommitsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
