package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Link link

swagger:model Link
*/
type Link struct {

	/* Rel rel
	 */
	Rel string `json:"rel,omitempty"`

	/* URL url
	 */
	URL string `json:"url,omitempty"`
}

// Validate validates this link
func (m *Link) Validate(formats strfmt.Registry) error {
	return nil
}
